
OPENAI_API_KEY = "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"








